apiVersion: apps/v1
kind: Deployment

metadata:
  name: events-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: quemasandy/events

---
apiVersion: v1
kind: Service
metadata:
  name: events-cluster-ip
spec:
  selector:
    app: events
  type: ClusterIP
  ports:
  - name: http
    port: 4005
    targetPort: 4005
