apiVersion: v1
kind: Service
metadata:
  name: events-svc-node-port
spec:
  type: NodePort
  selector:
    app: events
  ports:
  - name: http-events
    protocol: TCP
    port: 4005
    targetPort: 4005