apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: kblog.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-cluster-ip
                port:
                  number: 4002

          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-cluster-ip
                port:
                  number: 4000

          - path: /posts/?(.*)/comments
            pathType: Prefix
            backend:
              service:
                name: comments-cluster-ip
                port:
                  number: 4001

          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip
                port:
                  number: 3000
