apiVersion: apps/v1
kind: Deployment

metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: quemasandy/posts

apiVersion: v1
kind: Service
metadata:
  name: posts-svc
spec:
  selector:
    app: posts
  ports:
  - name: http
    port: 8080
    targetPort: 4000
  type: LoadBalancer
